### PR TITLE
LPS-118852 Use the getDefaultLanguageId instead of the getLanguageId

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
cc: @kevenleone

**Comment by kevenleone** [comment]
LGTM 🔥 

@jeyvison , can you re-open?

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
