### PR TITLE
LPS-93027 Auto SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
@jeyvison @brunobasto 
Cross posting this on the #ci slack channel as well.
The reason ci:test is not starting is because this pull request is sent your branch `jeyvison:pr-463` which isn't an upstream branch in the `liferay` user.

The pullrequest tester is configured to only be able to run against an actual upstream branch.

I've created a ticket to allow the webhook plugin to comment something when this happens so it won't appear unresponsive:
https://issues.liferay.com/browse/LRCI-392

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/470. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1049. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
