### PR TITLE
LPS-91985 Special characters cannot be used in Form field names

### PR DESCRIPTION
**Pull request by inacionery**
Hey @inacionery 

Could you please review this pull request?
Allowing only ascii alphanumeric characters is too restrictive, therefore I changed the rule to exclude only hyphen characters, as it was once decided in [LPS-49845](https://issues.liferay.com/browse/LPS-91985). 

Thank you and best regards,
István

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/69591
Thanks!

**Pull request closed without merging**
