### PR TITLE
LPS-91136 Index ddmstructure name in all available language to be consistent with other APIs

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/69293
Thanks!

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/878. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
