### PR TITLE
LPS-93229 Create CheckboxMultipleFieldType

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71045. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/77e4cd8c83f1~2...77e4cd8c83f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71048. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/10806da080ae~4...10806da080ae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71051. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/e1adf1a176b1~4...e1adf1a176b1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
