### PR TITLE
[DO NOT MERGE] LPS-90373 Removes SourceFormatter Suppression

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
restesting.. CI failed when trying to sign in..

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83103. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
