### PR TITLE
LPS-90373 Ignoring AlloyUI files

### PR DESCRIPTION
**Pull request by brunobasto**
cc @jbalsas

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68406. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
