### PR TITLE
LPS-78332 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Test fixes based on results from https://github.com/vicnate5/liferay-portal/pull/973, hopefully this is all we need. This branch is based off of https://github.com/jeyvison/liferay-portal/pull/50

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@jeyvison When the CI builds your changes, the new management bar is not there.

The CI does build the private modules, it is not just master CE. But I tried to disable the Kaleo EE modules and the problem is still present. Could you take a look?

**Comment by jeyvison** [comment]
Hi @vicnate5 , the change is only on CE not EE. I'll try to take a look at it locally. Can you see the new management bar locally in your  PC?

**Comment by jeyvison** [comment]
@vicnate5 , just tested it localy and it's looking good. Maybe some problem with ci:test:relevant?

**Comment by jeyvison** [comment]
Got it. Working on it now.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@vicnate5 , just sent the PR related to workflow-task-web: 

https://github.com/jeyvison/liferay-portal/pull/53

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@jeyvison All the test issues related to this pull are fixed.

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/58499. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
