### PR TITLE
[TECHNICAL-SUPPORT] LPS-91093

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Brian:
> The issue here is that,  in Calendar configured with Single Approver Workflow, when a user is invited for an Event, the Invitation mail for the event is sent to the user, before the approval of approver.
> 
> The reason for this issue is that we currently have no checks in-place that handles whether the calendar is approved or not. With our current implementation, the emails will be sent as soon as the creation happens.
> 
> The fix is to ensure that email notifications are only sent out when calendarBooking is approved. This maintains the existing behavior which is:
> 
> -Without workflow enabled for calendar, the calendarBooking is approved as it is created which means that the new implementation will handle email notification process basically the same as the old one.
> 
> It also introduces the new behavior which is:
> 
> -With workflow enabled, users are only sent email notifications once the booking is approved by the approver.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hey @SamZiemer , I'm forwarding this PR to @inacionery. He is the current leader of workflow( which calendar is under). Thanks for your fix :)

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/inacionery/liferay-portal/pull/167. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
