### PR TITLE
[Technical Support] LPS-86327 Auto SF.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/65552
Thanks!

**Pull request closed without merging**
