### PR TITLE
LPS-91898 Add integration test

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/466. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
