### PR TITLE
LPS-89260 considering json array value

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-app-builder/liferay-portal/pull/221. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/d6576a3d47d3~5...d6576a3d47d3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
