### PR TITLE
LPS-106361 buildLang

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82509. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/a91d1a511a53~1...a91d1a511a53) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82510. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/522a350b6e55~1...522a350b6e55) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/653. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/522a350b6e55~1...522a350b6e55) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
