### PR TITLE
LPS-90505 Add guest permissions for global templates to make them visible for non-global site administrators

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/68580
Thanks!

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83042. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
