### PR TITLE
LPS-82502 Overlapping Calendar Events

### PR DESCRIPTION
**Pull request by IstvanD**
Hello @jeyvison 

Could you please review this pull request for the Calendar portlet?

This fixes an issue when two events just start one after another, but one of the event is still overlapping the other in the scheduler view.

If event1 starts at, say, 11:53, and ends at 12:00, it will be covered entirely by event2 which start at 12:00.
No matter how small is the time frame of event1, the minimum size of the event's rectangle is of a half hour event.

The event's rectangle height cannot be shortened because the name label would hang over the frame.

Normally, if an event is overlapped by a later event, the later event's width will be reduced half a column.
However, in the above case, event2's width will not be reduced, since it starts just after event1 ended.

The intersection detection logic is implemented in the `intersects()` function in **aui-scheduler-view-day.js**
The approach I used for solving the issue is to override the function in `scheduler_models.js` where `SchedulerEvent` is extended, by extending the timeframe of the event (endDate + 30 minutes) whom with other event's are compared for collision.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hey @jeyvison 

I hope you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you,
István

**Comment by IstvanD** [comment]
Hi @jeyvison 

Is the any update on the status of the review?

Thank you!

Best regards,
István

**Comment by natocesarrego** [comment]
Hey @IstvanD and @hudakl,

I've processed all the information shared by István regarding the issue and the proposed solution and I can tell you that actually the events are not overlapping in this use case. Currently, if there is an event which ends at the same time another event starts, then the Calendar will handle it without problems. Although, the issue happens when the event that starts earlier has a short duration and it causes the event be rendered in an unsatisfactory way. Probably, it's caused due to  a minimum height value fixed in the code. Please, check the image below to better understand what is described above:

not overlapping events

- Can you please analyze the code to better understand how the event's height in the UI are defined?
- Can you focus in a solution for this specific use case, events with short duration?

Best.

**Comment by hudakl** [comment]
Hi @natocesarrego,

We discussed the possibility of shortening the event's height, but it would be too short to be correctly readable. If we are talking about very short duration it would even be hard to click on it.

That's why I decided to check if the two events overlapped with the half hour later start-time as well (considering that the minimum height fits a half hour period). During my tests I worked with three minutes long events, like in this specific use-case and the solution worked.

Furthermore, I checked the behavior in Google Calendar and it works like our calendar after the fix is applied.

Considering these, is the solution acceptable?

Thank you,
Laci

**Comment by natocesarrego** [comment]
Hi @hudakl,

We can change a little bit this solution and it'll attend our need and also work the same way as Google Calendar. 🙂 

The current issue is happening just for a specific use case, events with short duration (less than 30 minutes) and which end at the same time the following event starts. This should be the focus of our fix. I've tested the use case (please consider the same events of the gif available on my previous comment) with the proposed solution and with Google Calendar and I've got the following results:

**Google Calendar**
google calendar behavior

**Proposed solution**
liferay calendar behavior with proposed solution

The proposed solution fixes the issue, but it causes events which are not intersecting be rendered as they were intersecting and it doesn't happen in Google Calendar.

I've started a new solution, based on István's solution, which handles this specific use case, short duration event. Please take a look on it below:

```
intersects: function(evt) {
    var instance = this;
    var endDate = instance.get('endDate');
    var startDate = instance.get('startDate');
    var evtStartDate = evt.get('startDate');

    return (instance.sameStartDate(evt) || DateMath.between(
        evtStartDate, startDate, endDate) || instance._isShortDurationEventIntersecting(evtStartDate));
},

_isShortDurationEventIntersecting: function(evtStartDate) {
    var instance = this;
    var shortDurationEventIntersecting = false;

    if (instance.getMinutesDuration() < 30) {
        var endDate = instance.get('endDate');
        var earlierEvtStartDate = DateMath.subtract(
            DateMath.clone(evtStartDate), DateMath.MINUTES, 30);

        if (DateMath.compare(endDate, evtStartDate) ||
            DateMath.between(endDate, earlierEvtStartDate, evtStartDate)) {

            shortDurationEventIntersecting = true;
        }
    }

    return shortDurationEventIntersecting;
},
```
Then, I've repeated the same test with this new solution and the results are coherent with Google Calendar, see below:

liferay calendar desired behavior

I believe this solution may not be covering all corner cases of this use case, but it can be a start for you go ahead and improve it. Can you please check it and test?

Furthermore, sorry for delay the delivery of a final solution, but I'm trying to avoid regressions and behavioral changes that can affect other customers using Calendar.

Thanks for your patience.

**Pull request closed without merging**
