### PR TITLE
LPS-105478 Remove app name counter

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82879. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/a0cc624a058b~1...a0cc624a058b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82881. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/9770415ab6cf~1...9770415ab6cf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
