### PR TITLE
[TECHNICAL-SUPPORT] LPS-82965

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/78. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/331aafe7f951~1...331aafe7f951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61298. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/331aafe7f951~1...331aafe7f951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
