### PR TITLE
LPS-98183 Add test to check when a Data Definition is deleted, all entities related are deleted too

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78505. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/62647c03e91e~1...62647c03e91e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/618. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/5e2d3ba79a8d~3...5e2d3ba79a8d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79161. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/812e9c9236e5~3...812e9c9236e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
