### PR TITLE
LPS-95267 Use liferay-npm-scripts

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@brunobasto Any idea why it's broken?

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74032. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/a001a8c005c2~1...a001a8c005c2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74181. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/edd07cb69d2e~3...edd07cb69d2e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
