### PR TITLE
LPS-96064 Allow Data Provider requests through unauthenticated proxy servers.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @jeyvison,

From what I could see, the CI issues aren't related to this fix.

Best.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73698. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
