### PR TITLE
LPS-124653 After the migration we should take into account also "image" as infoDisplayFieldType

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:help

**Comment by jeyvison** [comment]
ci:test:data-engine

**Comment by jeyvison** [comment]
@dereckalexander Can you please verify if the DDL failures are related to this PR?

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by dereckalexander** [comment]
ci:test:relevant

**Comment by dereckalexander** [comment]
Hey @ealonso  and @jeyvison, this PR was responsible for the failure of this test **LocalFile.FormsJumpToPage#ViewPagesAfterJump**. It's is passing on EE Development Acceptance master. What I recommend is to run this test locally to find out if it's going to fail, because it may be a flaky one too.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
