### PR TITLE
LPS-83646

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-83646

From @joshuacords:

> This is the same fix as in https://issues.liferay.com/browse/LPS-83249
> ControlPanelWorkflowPortlet sets the WorkflowWebKeys.WORKFLOW_NAVIGATION_DISPLAY_CONTEXT for navigation.jsp when the page is accessed from the Control Panel, the UserWorkflowPortlet needs to do the same. I believe this is the last place where this change is necessary.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62016. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
