### PR TITLE
LPS-94809 Add build files

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74651. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ef6701dd94c0~2...ef6701dd94c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
