### PR TITLE
LPS-83662 Use ActionableDynamicQuery instead of traversing through the KaleoTaskAssignments

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

Following you suggestions in https://github.com/jeyvison/liferay-portal/pull/113#discussion_r214995840 it resorted to use ActionableDynamicQuery to fetch and delete the task assignments.
I'm not yet sure how to handle the other cases though.
Notifications about non-existent tasks are deleted automatically as the user views the Notifications portlet, and they also cannot view the task assignment once it's role is deleted.
WorkflowInstanceLinks contain the information on what asset should they operation (for example JournalArticle if the article has to be approved/rejected) but not on the roles.
Is there are way to fetch the information about the roles, so it could be checked if any of them are assigned to it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Reopening as the failed tests are not related to the fix.

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi Istvan, i did a quick test to show you my point about the notification but the deletion is not working. Please take a look at the gif attached. Don't worry about the role deletion notification, i didn't deploy the role bundle.

delete_role

**Comment by IstvanD** [comment]
Hi @jeyvison 

Thank you for showing your point.

I made the test with creating a user (UserA), and assigning him the Site Content Reviewer role. As the default Test user, I submitted a Web Content for publication, and both UserA and I received notifications, and we also received entries in our Workflow tasks.
Then I deleted the Site Content Reviewer role. As UserA, I could see the "Notification no longer applied", and then the notification was automatically deleted. UserA also could not see his assigned workflow task.
As the default Test user, the notification and the workflow task were still there.
I assume, that the default Test user has roles that enables him to review content, aside from the Site Content Reviewer role.

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62902. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
