### PR TITLE
[TECHNICAL SUPPORT] LPS-98519 Prepend path context in case URI starts with slash and it is missing

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Brian Chan rejected first pr, see: https://github.com/brianchandotcom/liferay-portal/pull/76236#issuecomment-515627026

I have implemented an alternative solution, changing only `PortalImpl.getStaticResourceURL(...)` code

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hey @jorgediaz-lr , it's ok to me but are these errors really unique?

**Comment by jorgediaz-lr** [comment]
Hi @jeyvison 

Yes, the errors are caused by my changes. I had a look to it and it is not correct to prepend context there as it breaks some portal functionalities.

I will have a look to it and I will resend

**Pull request closed without merging**
