### PR TITLE
[TECHNICAL-SUPPORT] LPS-96759

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-96759
> 
> The issue is that the value rendered using Liferay.Language.get() with key does not evaluate to the actual value. The key and call must be on the same line when using Liferay.Language.get() operation in JavaScript.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74716. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
