### PR TITLE
[TECHNICAL SUPPORT] LPS-91149

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-91149

[LPS-90362](https://issues.liferay.com/browse/LPS-90362) (sent in https://github.com/jeyvison/liferay-portal/pull/217) causes a regression:
> "Disable" searchable option is reset to "Keyword" after reopening "properties" tab.
> Data is correctly stored to database, but in case you reopen the field properties tab, radio button is reset to "Keyword".

Root cause of the issue is:

1. In case of setting indexType to disabled, it is saved successfully and it internally stores a empty string "".
2. If you edit again a field with indexType="", the forms UI resets indexType value to "keyword" because at javascript level (radio.soy.js) the empty "" is replaced by the predefinedValue, as it is considered a undefined value.

In order to solve this, I have restore previous solution, storing "none" for that kind of fields, and in order to avoid breaking webcontent logic (that was the original issue in LPS-90362), I have extended _DDM_FORM_FIELD_INDEX_TYPES values, see: https://github.com/jeyvison/liferay-portal/pull/264/commits/ca490eb9072f6c22420944e713f854360851fc31

So, we will have for indexType following values:
- Only forms => "none"
- Only webcontent => ""
- Both => "keyword" and "text"

In my opinion, changing webcontent indexType code from "" to "none" it is a bit risky, so it is better to maintain both

/cc: @linolaoj

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/69602
Thanks!

**Pull request closed without merging**
