### PR TITLE
[TECHNICAL-SUPPORT] LPS-92109

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:stop

**Comment by linolaoj** [comment]
submitted to https://github.com/brianchandotcom/liferay-portal/pull/69596
Thanks!

**Pull request closed without merging**
