### PR TITLE
LPS-95322 refreshing drag and drop to reset targets

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi, on commit 836044a65fa7d2787bf31cf72b4db1a775d39717, I'm refreshing the drag and drop because I was not able to sync correctly the drop targets using willReceiveProps.
Thanks!

**Comment by linolaoj** [comment]
The older pull request https://github.com/brianchandotcom/liferay-portal/pull/73043, only solved the drag up and down for ie11. This one also intend to solve the drag and drop after resize.

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/467. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
