### PR TITLE
LPS-77040 Calendar appointment date configuration is incorrect on Japanese localization

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Thank you so much, @jeyvison

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
The test failures are not related my changes.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/26. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55839. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
