### PR TITLE
[TECHNICAL-SUPPORT] LPS-99541

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@jeyvison I've been looking at this failing test and I'm not sure how you would want to handle it. Since it is a unit test the reference doesn't get satisfied. If I move this to an integration test it would find it successfully but it does not have access to the internal DDMRESTDataProviderSettings class. It could be rewritten to have a hard coded value for the class name to compare against but this doesn't seem ideal.

Do you have an idea as to how you would like to go about resolving the test failure? Beyond that, do you even like this new solution for the issue?

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/508. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
