### PR TITLE
LPS-101799

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82265 and my changes

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/646. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/e19e88fb6acc~2...e19e88fb6acc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82371. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/f34fa4b1dad6~2...f34fa4b1dad6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82483. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/617b49d0970d~2...617b49d0970d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
