### PR TITLE
TESTE

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:javadoc

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:help

**Comment by jeyvison** [comment]
ci:test:help

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@pyoo47 we are currently unable to add a new test suite on the CI. It was working the yesterday morning on this same PR (https://github.com/jeyvison/liferay-portal/pull/96#issuecomment-413586958)

**Comment by jeyvison** [comment]
ci:test:upgrade

**Comment by pyoo47** [comment]
@vicnate5 FYI we've backed out the suite name validation logic for now. We had some issues on master-private pull requests.

**Pull request closed without merging**
