### PR TITLE
LPS-96649 buildRest

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@jeyvison It should be merged after https://github.com/brianchandotcom/liferay-portal/pull/74455

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Pull request closed without merging**
