### PR TITLE
LPS-93027 Fixing Forms#ViewRepeatableTextFieldLabel

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
hey @alexcandidos . Can you please fix the SF related to Poshi please?

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
I can fix it here and push to the same branch

**Comment by brunobasto** [comment]
ci:test:sf

**Pull request closed without merging**
