### PR TITLE
LPS-93138 Move delete data definition tests

### PR DESCRIPTION
**Pull request by mclomello**
Jeyvison, could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72779. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/d0b2a0779a03~1...d0b2a0779a03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
