### PR TITLE
LPS-107710 Update data record version when update data record

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/83937

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84282. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/5b9341618ad2~2...5b9341618ad2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84284. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/7208ec62f8bc~2...7208ec62f8bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84285. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/afdca0ae441c~2...afdca0ae441c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
