### PR TITLE
[TECHNICAL-SUPPORT] LPS-89177

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-89177

Hi @jeyvison !
Solution is based on what we comment in https://issues.liferay.com/browse/PTR-553

Please let me know if you know any information.

Thanks!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/66975
Thanks!

**Comment by JosemariaMunoz** [comment]
Thanks a lot @linolaoj !

**Pull request closed without merging**
