### PR TITLE
LPS-121778 Disappearing, repetable Webcontent field

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @jeyvison ,

Could you please review this pull request?

Thank you @marcelabc the extraordinary help. :) 

Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @MarcellGyopos ! You're welcome :)
We are going to review your PR from Jeyvison repo, but our team created a repo to concentrate all work related: /liferay-data-engine/liferay-portal/pulls . Next time, you can send there 👍🙂

**Comment by marcelabc** [comment]
Hey @jeyvison,
This work is related to the PTR that I answered this week. This solution was the one that I tested and pointed to him, so LGTM

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
