### PR TITLE
LPS-77608 calendar-service: Reindex calendars belonging to the calendar resource when the resource is updated

### PR DESCRIPTION
**Pull request by leoadb**
CI results: "Unique failures" seem to be false negatives - https://github.com/marcellustavares/liferay-portal/pull/1902#issuecomment-384110735

https://issues.liferay.com/browse/LPS-77608

### CODE REVIEW

**Comment by BryanEngler** [comment]
hey @jeyvison, i just ran a rebase to upstream/master and i didnt have to resolve any conflicts.

https://github.com/BryanEngler/liferay-portal/commits/LPS-77608-reindex_calendar_resource

**Comment by jeyvison** [comment]
@BryanEngler That's weird. It's probably my repo. Let me check it here.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58772. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-data-engine/liferay-portal/pull/61. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/f4a754ef10db~1...f4a754ef10db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
