### PR TITLE
[TS] LPS-118423

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @natocesarrego ,

Can you help review this PR for a language key change to DDM? 

**Notes from @javalosjr96:**
> The issue was that the language key that the fieldset uses to display its type had not been updated and had remained as Fields Group. All that was changed was the the language key and gw BuildLang was ran.

Hopefully you're the right reviewer for these changes.

If not, can you let us know who we can forward this to?
Thanks!

### CODE REVIEW

**Comment by natocesarrego** [comment]
@jeyvison, this is an issue from App Builder, can you please review?

Thanks in advance.

**Comment by jeyvison** [comment]
@javalosjr96  @natocesarrego I'll take a look :) Thanks you folks ^^

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
Hello everyone, hope you all okay :)

I think we have a misunderstood here, with the name "Field Group" and "FieldSet" and it's very comprehensive why, but, even with the same type they are different.

Field Group, or Section (have a lot of names 🤯) and FieldSet, they both have the type: "fieldset", but the difference between then are the `ddmStructureId`

If the Field contains in `customProperties: {ddmStructureId}` so, it's a fieldSet, if not it's a FieldGroup

The fields of FieldGroup can be modified and FieldSet not.

See the picture for better understanding 
Screen Shot 2020-08-13 at 16 32 50

That's why it's not necessary to rename "fieldset-field-type-label" , so I have dropped both commits and will send a PR with the fix.

Any questions, we can talk on Slack ☺️

**Comment by kevenleone** [comment]
resent to: #841

**Pull request closed without merging**
