### PR TITLE
JaCoCo offline instrumentation

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
Hi @jeyvison, please let me know if the changes work for you.

If everything works as expected, I can take add this to our `gradle plugins` so other teams can easily use this feature too.  Does that seem ok to you?

**Comment by jeyvison** [comment]
Hi @petershin , it sounds awesome! I'll test it today and let you know  :)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by petershin** [comment]
Just cleaning up my branches.  Resent the pull: https://github.com/jeyvison/liferay-portal/pull/171

**Pull request closed without merging**
