### PR TITLE
LPS-91112 dynamic-data-lists-web - Remove jQuery

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69518. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
