### PR TITLE
LPS-90581 set empty value when it is not a number

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @jeyvison , in this fix I'm setting to empty the field value when the calculated result is not a number. I'm not sure if it is the best approach, maybe we should define some warning to show to the user on this kind of situation. Let me know what you think.
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hey @linolaoj . I believe it's enough for now.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68203. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83097. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
