### PR TITLE
LPS-87601 Changing iteration mode of list method

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/783. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/028319e30c1d~1...028319e30c1d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
