### PR TITLE
LPS-80992 Copy title translations when duplicate a workflow definition

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59602. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59603. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/491738cc820f~1...491738cc820f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-data-engine/liferay-portal/pull/65. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/8cee51919ed1~1...8cee51919ed1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
