### PR TITLE
[TECHNICAL-SUPPORT] LPS-93853 stopping event propagation

### PR DESCRIPTION
**Pull request by linolaoj**
https://issues.liferay.com/browse/LPS-93853

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71479. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
