### PR TITLE
LPS-97203 baseline

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75363. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/8e2f0d6acae6~1...8e2f0d6acae6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
