### PR TITLE
[TECHNICAL-SUPPORT] LPS-80232

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-80232

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by JosemariaMunoz** [comment]
Hi @jeyvison ,
I saw the same failures in my own git account https://github.com/JosemariaMunoz/liferay-portal/pull/29 before I sent you, but I think is not related to this PR (because it's related to Calendar, not related to Blogs).
Please let me know if you need something.
Thanks!

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hello @JosemariaMunoz . After some testing, i saw that the event is removed from the calendar after the declining and only appears back after a refresh on the page. Can you check that please?

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57813. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
