### PR TITLE
LPS-93561 Fix scope and custom query for search data record collection

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison could you review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71250. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
