### PR TITLE
LPS-93144 Delete Data Record Collection additional tests

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75373. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/b89b767d8684~1...b89b767d8684) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
