### PR TITLE
LPS-82338 Return the title of the definition considering Locale

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Failures not related to this pull.

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
