### PR TITLE
LPS-118277 remove form validation errors of ddm field when remove field

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-118277

Suggested reviewer based on https://github.com/liferay-echo/liferay-portal/pull/1847

From: @huynguyen-codeengine

> I have added one line of code to remove the form validation errors of the field after user remove field on UI in order to submit the form

### CODE REVIEW

**Comment by holatuwol** [comment]
Tests already passed:

https://github.com/liferay-echo/liferay-portal/pull/1847#issuecomment-672558241

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
