### PR TITLE
LPS-105743 Send dataListViewId to get data records page endpoint

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82876. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ca1a4aaa6243~1...ca1a4aaa6243) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
