### PR TITLE
LPS-116543 add nestedFields data on dataRecord

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/interaminense/liferay-portal/pull/129. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3dc217a72668~2...3dc217a72668) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
