### PR TITLE
[TECHNICAL-SUPPORT] LPS-99541

### PR DESCRIPTION
**Pull request by jonathanmccann**
@jeyvison Please let me know if you have any questions. We made a similar change in OAUTH2-251 (https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-scope-impl/src/main/java/com/liferay/oauth2/provider/scope/internal/ThreadLocalScopeContextScopeChecker.java#L169-L174) to resolve a similar upgrade issue.

/cc @achaparro

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@jeyvison Is there any update on this pull request?

**Comment by jeyvison** [comment]
Hello @jonathanmccann  :) I'm planning to review it today :)

**Comment by jonathanmccann** [comment]
@jeyvison Great, thank you for the update!

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76919. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
