### PR TITLE
[TECHNICAL-SUPPORT] LPS-78145

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Hello @jeyvison. I'm going off the information Renato posted that you were the new reviewer for Workflow related issues. If that's not the case, please let me know and I can forward this on to the correct person.

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal-ee/pull/24570

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
