### PR TITLE
LPS-98083 Add integration tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
I don't know why but the order of the commits is not the same that is showing in SourceTree...

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
I created a new one, but you can check the previous PR here: https://github.com/jeyvison/liferay-portal/pull/539

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76532. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76584. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
