### PR TITLE
LPS-98083 Add integration tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @jeyvison ,

After our talk, we decided to not reindex the delete method. Can you review, please?

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/140. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/0114220ac783~1...0114220ac783) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
