### PR TITLE
LPS-119263

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jeyvison can you resend? The exception and test method names seem messed up to me (inconsistent)

```
	@Test(expected = MustSetValidType.class)
	public void testInvalidFieldType() throws Exception {
```

```
	@Test(expected = MustSetValidIndexType.class)
	public void testInvalidFieldIndexType() throws Exception {
```

Please resend on top of my changes (feel free to revert my changes)

See https://github.com/jeyvison/liferay-portal/pull/869

**Comment by brianchandotcom** [comment]
See https://github.com/jeyvison/liferay-portal/pull/869

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/877. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/4fc5e3480203~1...4fc5e3480203) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
