### PR TITLE
[TECHNICAL-SUPPORT] LPS-92478

### PR DESCRIPTION
**Pull request by rafaprax**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-92478
> https://issues.liferay.com/browse/LPP-33367
> 
> Because ResourceURL by [default copy the parameters of the request](https://github.com/liferay/liferay-portal/blob/d869b10ee301fd02782efd393c178bdb4623d405/portal-impl/src/com/liferay/portlet/internal/PortletURLImpl.java#L1250-L1252), the URL can become too long for Captcha to accept. So we need to setCopyCurrentRenderParameters(false).

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70916. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/07f23ef7a28a~1...07f23ef7a28a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
