### PR TITLE
LPS-104943 SF

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82967. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/fce818424517~1...fce818424517) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
