### PR TITLE
LPS-98549 Uses the boolean value

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
hello @ricardocousolr :) Could please take a look at the failing tests, specially the DDMIndexerImpl ones? Thanks :)

**Comment by ricardocousolr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Please see #546

**Pull request closed without merging**
