### PR TITLE
LPS-83662 Site Content Reviewer role can be deleted despite Workflow Definition associated with it

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison

Could you please review this pull request.
Although the changes affect the Roles Admin Portlet, the solution fixes an issue related to Workflow, thus I'm sending the pull request to Workflow component.

Please let me know if you asset that it should rather be sent to the Roles team.

This is the same change as https://github.com/jeyvison/liferay-portal/pull/81, but I corrected the part that fails the test.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
hi @IstvanD , sorry for the delay in answering you, i was sick, at home. I believe it should be sent to the Roles team since all the changes happened there. But feel free to cc me in the PR you send to them or ask me anything about it.

Thanks a lot for your fix!

**Comment by IstvanD** [comment]
Hi @jeyvison 

Many thanks for your answer. I hope you are getting better.
I'll send the pull to the Roles team, then.

Best regards,
István

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-app-builder/liferay-portal/pull/94. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/40015b4f8b31~1...40015b4f8b31) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
