### PR TITLE
LPS-118843 DDFormField fieldNamespace is not guaranteed to be unique

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @jeyvison 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
Hi @jeyvison 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/848. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/06fcbb183429~1...06fcbb183429) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
