### PR TITLE
[TECHNICAL-SUPPORT] LPS-98372 Fix integration tests

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related tickets:
https://issues.liferay.com/browse/LPS-98372

Note: @jeyvison, don't be alarmed if you see errors on `DDMRESTDataProviderTest.testGetCountryByName` and `DDMRESTDataProviderTest.testGetCountryByNameUsingGuestWithViewPermission`. Those were already happening by the time I started developing the fix.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:upgrade

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
Forgot to run the baseline

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:upgrade

**Comment by rodrigopaulino** [comment]
Hope it's good to review now. :)
Thanks.

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/507. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
