### PR TITLE
LPS-108755

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jeyvison see https://github.com/brianchandotcom/liferay-portal/pull/87423

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/712. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/45d5eecd513a~1...45d5eecd513a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/713. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/1871b2d038ac~1...1871b2d038ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
