### PR TITLE
LPS-90047 not needed

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @jeyvison , I'll include the metal part of the fix and push the changes.
Thanks!

**Comment by linolaoj** [comment]
Hi @jeyvison, I've pushed the changes.
Thanks!

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68385. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68468. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/7a628dc5f6a6~1...7a628dc5f6a6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
