### PR TITLE
LPS-96149 Ensure destructor method is called to remove any remaining handler

### PR DESCRIPTION
**Pull request by jkappler**
Hi @jeyvison, this touches ddm_form.js, so I prefer to run this through you first.

Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73914. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
