### PR TITLE
[TECHNICAL-SUPPORT] LPS-79201

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-79201

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
Hi @jeyvison ,
I think this failures are not related to this PR but these others:
https://loop.liferay.com/home/-/loop/feed/10592912
https://loop.liferay.com/home/-/loop/feed/10662264
Thanks!

**Comment by jeyvison** [comment]
hi @JosemariaMunoz . Yeah, its related to another issue. By the end of the week i'll be reviewing this PR  ;)

**Comment by JosemariaMunoz** [comment]
Ok, thank you very much @jeyvison !!

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56918. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-data-engine/liferay-portal/pull/38. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
