### PR TITLE
LPS-114151 Ignore test for now

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
cc: @ealonso @drewbrokke

**Comment by jeyvison** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Hi @jeyvison, I sent the ignores here: https://github.com/brianchandotcom/liferay-portal/pull/89008. Brian merged an hour ago.

**Comment by patriciajeanperez** [comment]
ci:stop

**Comment by jeyvison** [comment]
Thanks a lot @patriciajeanperez  =D

**Comment by jeyvison** [comment]
ci:stop

**Pull request closed without merging**
