### PR TITLE
LPS-114779

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt

See DataDefinitionResourceTest

```
	@Test
	public void testGetDataDefinitionPermissionsPage() throws Exception {
		DataDefinition postDataDefinition =
			testGetDataDefinition_addDataDefinition();

		Page<Permission> pagePermissions =
			dataDefinitionResource.getDataDefinitionPermissionsPage(
				postDataDefinition.getId(), RoleConstants.GUEST);

		Assert.assertNotNull(pagePermissions);
	}
```

I'm curious why BaseDataDefinitionResourceTestCase didn't generate testGetDataDefinitionPermissionsPage

Can you fix REST Builder so it at least generates a test method for every resource method.

Then, cany ou update DataDefinitionResourceTest and add @Override to testGetDataDefinitionPermissionsPage

In general, for *ResourceTest, I like every test method to have @Override

@jeyvison please fix my commits and coordinate with @nhpatt to resend to me.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/778. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/0a17ddf7c30d~2...0a17ddf7c30d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
