### PR TITLE
LPS-93027 Sort

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74499. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c3ed012a79e5~1...c3ed012a79e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
