### PR TITLE
LPS-93141 Add tests for data definition rule functions

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison could u review this pr?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75053. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/51b5778bfa3a~3...51b5778bfa3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/mclomello/liferay-portal/pull/3. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/51b5778bfa3a~3...51b5778bfa3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
