### PR TITLE
LPS-117159 SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by adolfopa** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
As i talked with @adolfopa , I'm holding this one 'till the release since it changes DDMIndexer

**Comment by adolfopa** [comment]
Hey @jeyvison,

Can you review this pull to include the changes in 7.4?

Thanks!

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
