### PR TITLE
LPS-98083 Add integration tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @jeyvison ,
The unique failure mentioned in the https://github.com/brianchandotcom/liferay-portal/pull/76532 was already failing before my PR was sent.
You can check testray: https://testray.liferay.com/home/-/testray/case_results/710874511/history?tab=result&hideFilterPin=true

**Comment by jeyvison** [comment]
sent in https://github.com/brianchandotcom/liferay-portal/pull/76584 Thx :)

**Pull request closed without merging**
