### PR TITLE
LPS-87512 Makes sure we don't unpublish an already published form by mistake

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67208. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
