### PR TITLE
[TECHNICAL-SUPPORT] LPS-96793

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74493. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/18790a42c81a~1...18790a42c81a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74494. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/61ee81bd5876~1...61ee81bd5876) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
