### PR TITLE
LPS-109716 baseline

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by gabrielwas** [comment]
cc/ @brunofarache

**Comment by jeyvison** [comment]
ci:foward

**Comment by jeyvison** [comment]
ci:help

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:foward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/86762. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/79a69054b8b4~8...79a69054b8b4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@jeyvison keep in mind, relevant runs a lot more tests for DDM now, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/test.properties

Please try not to run ci:forward more than once. If tests fail, they should be addressed with a fix, quarantine, or ignore.

cc/ @alexcandidos @cvanut

**Comment by jeyvison** [comment]
got it @jpince  :) I'm running it again since there was a change in how tests run.

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/687. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
