### PR TITLE
[TS] LPS-112077 Audit portlet does not display user information from workflow activity

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-112077](https://issues.liferay.com/browse/LPS-112077)

Hi @jeyvison ,

I am sending this to you, because the issue is workflow related. Please let me know if you think it should go to someone else.

In short, the issue is that AuditEvent records don't contain the approver data because AuditRequestThreadLocal is not populated properly.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hiello @istvansajtos  :) Soory for the delay in answering you. Can you please forward this PR to @Inacionery . I'm no longer in workflow team :)

**Comment by istvansajtos** [comment]
Thanks @jeyvison ! I've forwarded to https://github.com/inacionery/liferay-portal/pull/601

**Pull request closed without merging**
