### PR TITLE
LPS-90832 Don't overwrite the operand's label value if it already exists

### PR DESCRIPTION
**Pull request by cleydyr**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/68583
Thanks!

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-app-builder/liferay-portal/pull/255. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/49d2a97c2fd0~1...49d2a97c2fd0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
