### PR TITLE
LPS-87331 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hello @jeyvison 

After a lot of tries, I chose  (I think) the easiest solution: fix the front-end tier instead of server one. So it summarizes to generate valid form elements names according to defined grammar.

References:
https://issues.liferay.com/browse/LPS-87331
Same issue but different fix in 7.0.x (because of refactored code): https://github.com/liferay/liferay-portal-ee/pull/11732

Kind regards.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/66745
Thanks!

**Pull request closed without merging**
