### PR TITLE
Revert "LPS-113779 restrict filter to exclude /o endpoints"

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test-sf

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
cc: @nhpatt @shuyangzhou reverting https://github.com/brianchandotcom/liferay-portal/pull/89111. Caused https://issues.liferay.com/browse/LPS-114269

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just started reviewing :)

**Pull request closed without merging**
