### PR TITLE
LPS-91406 firefox needs explicit event

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:teste:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68818. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
