### PR TITLE
[TECHNICAL-SUPPORT] LPS-90444

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @diana-lin 

Notes from Diana:

> https://issues.liferay.com/browse/LPS-90444
> 
> **Problem**: Unable to add a mathematical expression for the Calculate action in Form Rules.  Clicking on integers or operators in the calculator UI does not produce any results in IE11.  This is because IE does not support the Javascript method `.includes`.  [See documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility).
> 
> **Solution**:  Replace `.includes` with `.indexOf`.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/68028
Thanks!

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83095. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
