### PR TITLE
LPS-97221 Delete data record collections by structure ID

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75310. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/61fa404fa2ea~1...61fa404fa2ea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75313. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/9fe4137445a7~1...9fe4137445a7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
