### PR TITLE
[TECHNICAL-SUPPORT] LPS-96425

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/420. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/77c48c7ba94d~2...77c48c7ba94d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74243. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/869f4d013f4f~1...869f4d013f4f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
