### PR TITLE
[TECHNICAL SUPPORT] LPS-96833 partial revert of LPS-87084

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-96833
https://issues.liferay.com/browse/LPS-87084

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74751. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ad1ae1d6d878~1...ad1ae1d6d878) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
