### PR TITLE
LPS-96237 Add warning to inform the user that dates and times are only exported in GMT

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Hey, @jeyvison. Could you please run the `buildLang` task for me, since I don't have the MS Azure translation service configured?
Thanks.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74242. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/67ad7d2eb35f~2...67ad7d2eb35f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
