### PR TITLE
LPS-90984 removing data provider configuration icon

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/450. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
