### PR TITLE
LPS-92613 DDM field name can contain non-alphanumeric characters

### PR DESCRIPTION
**Pull request by inacionery**
Hey @inacionery 

Could you please review this pull request?

[LPS-91985](https://issues.liferay.com/browse/LPS-91985) failed on a test case, because it allowed special  (ie. non-alphanumeric) characters in field names.

I changed the validation logic to the one used in `normalizeKey()`, so again only alphanumeric characters are allowed, but those can be Unicode, not just ASCII.

Thank you and best regards,
István

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hey @jeyvison 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by jeyvison** [comment]
hi @IstvanD , I'm really sorry for the delay in reviewing your PR but i'll try to review it 'till the end of the week.

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/70192
Thanks!

**Pull request closed without merging**
