### PR TITLE
[TECHNICAL SUPPORT] LPS-93842

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-93842

In case a language is removed from instance configuration, LanguageUtil.isAvailableLocale returns false and JSON is considered as UnlocalizedValue.

To avoid that, I am changing **LanguageUtil.isAvailableLocale(key)** to **ArrayUtil.contains(PropsValues.LOCALES, key)**. PropsValues.LOCALES contains all languages that can be added/removed to a instance configuration

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71777. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
