### PR TITLE
LPS-117972 Use the default locale of the existing form and if it does not exist prioritize the site default locale

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-117972

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/803. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/96fa82fdd1ac~2...96fa82fdd1ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
