### PR TITLE
LPS-96649 Update packageinfo

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74708. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ba109299d6f7~1...ba109299d6f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
