### PR TITLE
LPS-110840 build service

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
talking with Alex it seems that CI rebases the branch with local master not upstream. I updated my master branch and i'm running the tests again.

**Comment by jeyvison** [comment]
ci:forward

**Comment by jpince** [comment]
@jeyvison `UpgradeDynamicDataMappingTest` was just reactivated by @leoadb a few days ago
https://github.com/brianchandotcom/liferay-portal/commit/2bade355db6f81b4737563445cd387fbab84f2dc#diff-902a91349cb32901d0f481b261be003c
Can you please look into it before retesting again? It failed in all of your retests

**Pull request closed without merging**
