### PR TITLE
LPS-93268 DDM field name can contain hyphen

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hey @IstvanD . Can you please fix the SF issue,  please? Thanks!

**Comment by IstvanD** [comment]
Hey @jeyvison 

Sorry, I have fixed it and pushed it.

Best regards,
István

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71149. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/229044622aca~1...229044622aca) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
