### PR TITLE
[TECHNICAL-SUPPORT] LPS-88265

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66253. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66256. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/f1ed2586618b~1...f1ed2586618b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
