### PR TITLE
LPS-93027 Adds missing bundler dependencies

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1045. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ac2e7730a371~7...ac2e7730a371) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
