### PR TITLE
LPS-96606 Update packageinfo files

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@jeyvison It seems not related.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74309. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/10ae1198bd14~3...10ae1198bd14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
hey @leoadb , please see my changes. Thanks.

**Pull request closed without merging**
