### PR TITLE
[TECHNICAL-SUPPORT] LPS-99238

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hello @jonathanmccann . Can you please send the PR to @rafaprax ? He's in the workflow team that is responsible for the calendar component. Thx!

**Comment by jonathanmccann** [comment]
@jeyvison Thank you for letting me know.

**Pull request closed without merging**
