### PR TITLE
[TS] LPS-122681, LPS-122683

### PR DESCRIPTION
**Pull request by ChrisKian**
Related Issue: https://issues.liferay.com/browse/LPS-122683

Forwarded from https://github.com/natocesarrego/liferay-portal/pull/901

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Hello, @ChrisKian and @kevhlee  , thanks a lot for your fix! For all fixes related to DDM ( that do not involve Forms) can you please send to liferay-data-engine/liferay-portal? I'm gonna forward this one and we can apply this policy for the next PR's. Thanks a lot =D

**Pull request closed without merging**
