### PR TITLE
[TECHNICAL-SUPPORT] LPS-81852

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/707. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
