### PR TITLE
LPS-93861 Create Data Layout HTML

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73196. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/92dc084c8a80~1...92dc084c8a80) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73199. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/e5c94ca45a6c~2...e5c94ca45a6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/364. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/9bbc13079239~3...9bbc13079239) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73205. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/61fe946c0575~3...61fe946c0575) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
