### PR TITLE
LPS-120598 DDL Records can be added on the Live Site despite live editing being disabled

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @jeyvison 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @jeyvison 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hi @jeyvison 

Bypassing staging check for ADD_RECORD actions has been added by [LPS-66069](https://issues.liferay.com/browse/LPS-66069).
However, this is not necessary because setting the `staging.live.group.locking.enabled` property `false` enables adding records on Live Sites.

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
