### PR TITLE
LPS-93027 Fix unit tests

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
:)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74767. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/8ab2c8fda69a~1...8ab2c8fda69a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
