### PR TITLE
LPS-98468 Baseline

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @jeyvison ,
I renamed like Brian suggested and did your suggestions (SF commit in https://github.com/brianchandotcom/liferay-portal/pull/76605)

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/76686. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/20dd342fa5cf~5...20dd342fa5cf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
