### PR TITLE
LPS-114921 Move logic to Component to avoid race condition during upgrade using *ServiceUtil

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:stop

**Pull request closed without merging**
