### PR TITLE
LPS-108395 extract to SPI* classes so other bundler can call data engine methods in same transaction

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/679. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/a63979d97a5c~2...a63979d97a5c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/716. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/1b983092bb28~2...1b983092bb28) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
