### PR TITLE
[TS] LPS-106505

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPP-35670
https://issues.liferay.com/browse/LPS-106505

From @wanderlast:

> This fix covers an edge case for the overall issue outlined in the body of the LPP. The LPP and the initial LPS (https://issues.liferay.com/browse/LPS-98228) addressed the issue that HTML fields using a CKEditor editors would lose their contents when dragged and dropped. However, CS reported that the client was using these HTML fields nested in other fields. This fix insures that the nested fields are also checked for HTML fields and that those fields are recreated as well.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hello @ChrisKian :) 

I Applied you fix and follow the steps described in: https://issues.liferay.com/browse/LPS-106505 but I'm getting the following problems in the console:

Captura de pantalla 2020-01-07 a la(s) 14 43 04

Your fix applied:

Captura de pantalla 2020-01-07 a la(s) 14 45 44

Let me know if I am missing something.

**Comment by ChrisKian** [comment]
Hey @jeyvison,

After speaking with @wanderlast, she's determined the issue is reproducible sporadically and will work on a solution.  I will close PR now.

**Pull request closed without merging**
