### PR TITLE
LPS-99754 Detach the function saveTemplate on destroyPortlet

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/77291. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
