### PR TITLE
LPS-119263-SF

### PR DESCRIPTION
**Pull request by noornajj**
Made suggested change from Brian Chan's [comment](https://github.com/brianchandotcom/liferay-portal/pull/93738#issuecomment-686640603)

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
