### PR TITLE
[TECHNICAL SUPPORT] LPS-94545

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-94545

When a form is added to a page, languageId parameter is always empty and getDefaultLanguageId() returns the default locale of ddmForm, so title and description is displayed in that language and forms fields are displayed in the correct one returned by getLocale(request, ddmForm)

To avoid this issue, with this change in case languageId parameter is empty or invalid, we fallback to existing getLocale(request, ddmForm) method that internally handles correct behavior.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72351. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
