### PR TITLE
LPS-118436 Add locale as request attribute

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
cc: @interaminense

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:forward

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
resent to: https://github.com/jeyvison/liferay-portal/pull/817

**Pull request closed without merging**
