### PR TITLE
LPS-106893 Implement nestedMoveField for handling nested field move

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @jeyvison 

could you please check my fix and push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/1003. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/91779160eb59~2...91779160eb59) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
