### PR TITLE
[TECHNICAL-SUPPORT] LPS-89861

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71710. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c3c355d069da~1...c3c355d069da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
