### PR TITLE
LPS-84923 Integration tests

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
@jeyvison, just so you know, the failure related to the new test DDMFormDisplayContextTest.testGetDDMFormHTML is not an implementation error.
Not sure if it's a CI problem or the current master is broken. But, once this is fixed, the pull request is good to be retested.
Thanks. :)

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Looking into the related failure.

**Pull request closed without merging**
