### PR TITLE
LPS-87097 Update tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:test

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test

**Comment by marcelabc** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by marcelabc** [comment]
LGTM

**Comment by marcelabc** [comment]
Pull request submitted to brianchandotcom#65300 .

**Pull request closed without merging**
