### PR TITLE
[TECHNICAL SUPPORT] LPS-98906 Prepend path context of Liferay webapp

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Hye @jorgediaz-lr . Just so you know, i didn't review this PR yet because the problem it solves  seems to be very close to the other one you sent to me. Am i rigth? If i should review it anyway, just le me know. thx!

See https://github.com/jeyvison/liferay-portal/pull/547

**Comment by jorgediaz-lr** [comment]
Hi @jeyvison 

Please review this PR as it is a different issue, the other PR was related to CSS and this one is related to JS submit.

Thank you

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76527. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/7cf5b9c81b00~1...7cf5b9c81b00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
