### PR TITLE
LPS-105980 Save applied filters to data list view

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/643. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/fb0bfe014c46~4...fb0bfe014c46) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82298. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/fb0bfe014c46~4...fb0bfe014c46) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
