### PR TITLE
LPS-95081 check if options have already been loaded

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73904. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/820b6d635c71~1...820b6d635c71) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
