### PR TITLE
[TECHNICAL SUPPORT] LPS-90362

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-90362

I have reverted part of the implemented changes to avoid problems with existing webcontent code that relies in DDM infrastructure.

For "not indexed" fields, instead of using indexType = "none", I have changed it to indexType = StringPool.BLANK that is the value used in webcontent.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/68006
Thanks!

**Pull request closed without merging**
