### PR TITLE
LPS-96186 buildTaglib

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74943. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/fd9e8b040a1c~2...fd9e8b040a1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
