### PR TITLE
LPS-91697 SF

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Hey @jeyvison @inacionery
The test fail does not look related to those commits

/cc @LuismiBarcos

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/69593
Thanks!

**Pull request closed without merging**
