### PR TITLE
LPS-117004 Remove validation of empty data list view

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/92021. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
