### PR TITLE
[TECHNICAL-SUPPORT] LPS-89320

### PR DESCRIPTION
**Pull request by SamZiemer**
Relevant ticket:
https://issues.liferay.com/browse/LPS-89320

This fix changes a call used during the forms upgrade from a get to a fetch when trying to retrieve a user.

We previously used fetch in this same place, but I believe it was accidentally changed during this commit: https://github.com/liferay/liferay-portal/commit/e887c9e5fc5a5d3eddb077232af49e4470ec8440#diff-93c43c008824c74462cfa65d041e57b7R703

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:test:upgrade

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/67013
Thanks!

**Pull request closed without merging**
