### PR TITLE
LPS-93027 Not needed

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@brunobasto @jeyvison unit test failures seem unique to this pull (I don't see them in upstream). Will they be resolved by a final PR?

**Comment by jeyvison** [comment]
Hi @jpince , i'll resolve them now.

**Comment by jeyvison** [comment]
ci:help

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:backend

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74662. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/692c46d0b3d5~1...692c46d0b3d5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74697. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/1bc46092771f~2...1bc46092771f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74699. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/72d14c4ef928~1...72d14c4ef928) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
