### PR TITLE
LPS-83034 Move logic to update event time to a new method to avoid code duplication.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61967. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c3238a2d9194~1...c3238a2d9194) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
