### PR TITLE
LPS-98468 Baseline

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
I created a new one, but you can check the previous PR here: https://github.com/jeyvison/liferay-portal/pull/550

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @jeyvison , I just rebased my branch and there are no conflicts anymore. 
Can you review, please?

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
@jeyvison can you review please?

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76605. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/b1b29e065922~1...b1b29e065922) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
