### PR TITLE
Lps 119263

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @noornajj:
> https://issues.liferay.com/browse/LPS-119263
> 
> The issue here was that the validateDDMFormFieldType method did not validate whether the field type being added is one of the predefined types in DDMFormFieldType.
> To fix the issue, I added a check on whether the field type is one of the predefined types. If not, then I added a new DDMFormValidationException class, MustSetValidTypeForFieldType, that is thrown.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/867. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/6fdcaca547de~1...6fdcaca547de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
