### PR TITLE
LPS-93851 Prefer using Object.keys instead of for..in

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hey @jeyvison!

I found this small fix for https://issues.liferay.com/browse/LPS-93851
Could you verify that it is working and send it to bchan?

Thanks!

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
sure, thanks a lot @p2kmgcl :)

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@alinedoleron, can you please take a look at this fix?

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Hi, @jeyvison. LGTM!

**Comment by alinedoleron** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/71716

**Pull request closed without merging**
