### PR TITLE
LPS-93135 Move tests scenarios for list data definition

### PR DESCRIPTION
**Pull request by mclomello**
Jeyvison, could u review this pr?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72778. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/258d00e8ebf1~1...258d00e8ebf1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
