### PR TITLE
LPS-90938 Updates test snapshots

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
@jeyvison Failing JS test is unrelated. It from the page fragments component

layout.layout-content-page-editor-web.test.js.utils.FragmentsEditorIdUtils #encodeAssetId should add an encoded id to a given asset object (from Jest)

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/69716. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
