### PR TITLE
LPS-92556

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73161

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73236. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/43e380a7c45b~2...43e380a7c45b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73283. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/86dd48a59f1a~2...86dd48a59f1a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
