### PR TITLE
LPS-84119 Sort parameters

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Hey @jeyvison I got this PR from @hhuijser applying SF to some Soy files. I've checked WEM related ones, but there are also some from your team. Could you review them and then send the PR to @danielkocsis (there are changes on their modules too).

Thanks!

**Comment by jeyvison** [comment]
Hey @brunobasto, can you please take a look at this one? Thanks, man.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @hhuijser. Thanks for sending this over. I noticed something off about this PR. There are a few places where the soy parameter declarations are duplicated and portal fails to build. Like here https://github.com/jeyvison/liferay-portal/blob/3ca6609138c7bc3777d713616040260fb6be6fdc/modules/apps/change-tracking/change-tracking-change-lists-configuration-web/src/main/resources/META-INF/resources/js/ChangeListsConfiguration.soy#L8

At first I thought I might have resolved conflicts badly, bud then I noticed errors even on files that had no conflicts at all. Then I came to check your PR and saw that there were indeed duplicated declarations. Was this done by the auto SF tool?

**Comment by hhuijser** [comment]
@brunobasto @p2kmgcl 

The original pull that I sent does not have those duplicates.
As it's gone through a few reviewers, things have changed (@p2kmgcl, looks like you incorrectly resolved conflicts?)

See https://github.com/p2kmgcl/liferay-portal/pull/371/commits/5401d2bd26ada3a4d64fff707a5de2bcde481c49

This pull does not have the duplicates.

**Comment by hhuijser** [comment]
Generated and resend here: https://github.com/jeyvison/liferay-portal/pull/442

**Pull request closed without merging**
