### PR TITLE
LPS-87353 Do not reformat the number when building context or saving forms answer

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
With modifications suggested on #501

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75371. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/b3a5b8633de8~3...b3a5b8633de8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
