### PR TITLE
LPS-93971 Create OptionFieldType

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison

### CODE REVIEW

**Comment by mclomello** [comment]
@brunofarache

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71773. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
