### PR TITLE
LPS-96186 buildTaglib

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/464. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/6b0c3cd08c1e~1...6b0c3cd08c1e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
