### PR TITLE
LPS-87084 Form portlet form selector does not see unstaged forms

### PR DESCRIPTION
**Pull request by rafaprax**
Hey @rafaprax 

Could you please review this pull request?
I fixed the tests that failed in https://github.com/rafaprax/liferay-portal/pull/917

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @jeyvision

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test

**Comment by marcelabc** [comment]
ci:test:staging

**Comment by IstvanD** [comment]
Hello,

Are the failed tests related to the solution?

Thank you and best regards,
István

**Comment by marcelabc** [comment]
ci:test:staging

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @IstvanD , I ran the tests locally from DDMStructureLocalServiceTest and they all passed on Master and also with this fix, so those failed tests should not be related with your solution. I'm going to try to forward this pull today.
Thanks!

**Comment by linolaoj** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/65545
Thanks!

**Pull request closed without merging**
