### PR TITLE
[TECHNICAL SUPPORT] LPS-94720 SF

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @jeyvison,

I've just reviewed this pull and it looks good to me. Can you please double check?

Additionally, there are no regressions related to this fix, as you can see [here](https://github.com/natocesarrego/liferay-portal/pull/144#issuecomment-489200348).

Thanks.

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72687. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72688. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
