### PR TITLE
LPS-114853 buildLang

### PR DESCRIPTION
**Pull request by ealonso**
Hey @jeyvison,

As part of the changes on Global Menu we are moving the App Builder to Applications. I tried to make all the changes but it is possible that I missed something.

Could you please take a look?

An screenshot of how it's looks like:

Form_-_Control_Panel_-_Liferay

A couple of things that we should o take into account:

- At this point the new apps in Global Menu are showing within a Parent Category, we are working in the new definition with Angelo, Jorge and Victor.
- Maybe we need to rethink this screen, since Global Menu is not in the Product Menu:

New_App_-_Control_Panel_-_Liferay

Please let me know if you have any question.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/757. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/6406a31214e0~2...6406a31214e0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/761. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/28b837c22252~2...28b837c22252) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
