### PR TITLE
LPS-118502 fixed broken tests due the changes made on TranslationManager and AUI

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci;forward

**Comment by interaminense** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/828. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/67a30ba742d2~1...67a30ba742d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
