### PR TITLE
[TECHNICAL-SUPPORT] LPS-79943

### PR DESCRIPTION
**Pull request by jonathanmccann**
@jeyvison,

For this fix I tried emulating the behavior that Google calendar follows in that no notifications are sent for the master booking.

The core of the issue is that if the calendar booking creator is also invited to the event, that user has two calendar booking objects attached to them: one as a child calendar booking and one as the master booking. With this change, the child calendar booking notification will still be sent but the master one will no longer be sent so the user only receives one email notification for their personal calendar.

Please let me know your thoughts on this as there are a number of ways to resolve this issue but this seemed the most straight forward.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:start

**Comment by jeyvison** [comment]
ci:teste:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
cc: @pcwhite

**Comment by jonathanmccann** [comment]
Looks like the tests are expecting a non-invited calendar booking creator to be notified. If you agree that this is the correct fix I can change the tests and push that up, just let me know one way or the other.

**Comment by jeyvison** [comment]
ci:open

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
Hi @jonathanmccann , Sorry for the delay in review this PR. I agree with the fix. Could you please fix the tests so they reflect this change? Thanks :)

**Comment by jeyvison** [comment]
@jonathanmccann , can we talk via Slack to discuss about this one?

**Pull request closed without merging**
