### PR TITLE
[TECHNICAL SUPPORT] LPS-107051 DDM structures with translations cannot be saved in case you add a radio or select field

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-107051

In order to solve this issue, in case any language is missing, I am getting the text from default one.
In the first commit https://github.com/jeyvison/liferay-portal/pull/669/commits/02d2d5ff99b83da5caac779e9826582acfcca606, I have just copied the code from here:
 - https://github.com/liferay/liferay-portal/blob/9d9fde2b59f8d50feed7ccd01519dbd8edf064a9/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/custom_fields.js#L1177-L1205

As it is the same code in both places, I have extracted it to a new method (see commit https://github.com/jeyvison/liferay-portal/pull/669/commits/a057e125bb959d0ab60b158ec6e029eee945e923) and made some simplifications to it (see commit https://github.com/jeyvison/liferay-portal/pull/669/commits/cde9893f0ed73fa254acfc91540bdde5711d9eaf).

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hello @jorgediaz-lr :) While @natocesarrego is absent, @rafaprax will be in charge to review the PR's for this week. I'm forwarding it to him. Thanks for you fix :)

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/1006. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ece9a6bcaba1~1...ece9a6bcaba1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Thank you @jeyvison !!

**One question:** This morning I saw this post: https://loop.liferay.com/web/guest/home/-/loop/feed/20535445 but there is no information about DDM

Which team is the owner of DDM?

Thank you

**Comment by jeyvison** [comment]
@jorgediaz-lr DDM, DDL, and pools are under Forms' umbrella :)

**Pull request closed without merging**
