### PR TITLE
[TECHNICAL SUPPORT] LPS-98828

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-98828
Resent from https://github.com/jonathanmccann/liferay-portal/pull/1811

This issue is currently a blocker. I was able to see that it resolves the issue. Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76600. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76601. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3c1687ba4b8b~1...3c1687ba4b8b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
