### PR TITLE
[TECHNICAL-SUPPORT] LPS-98137 Clear localizedValue as well when repeating field

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related tickets:
https://issues.liferay.com/browse/LPS-98137

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75837. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
