### PR TITLE
[TECHNICAL-SUPPORT]  LPS-99216

### PR DESCRIPTION
**Pull request by matthewchan1**
https://issues.liferay.com/browse/LPS-99216

Hello @jeyvison,
 
This PR contains requested changes as per the pull sent here: 
https://github.com/jeyvison/liferay-portal/pull/572

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:sf

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
Hello @jeyvison,

I just wanted to check if there are any updates as to the status of this review. Please let me know if I can do anything. Thanks.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77165. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/0967fd9c110a~1...0967fd9c110a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
