### PR TITLE
[TECHNICAL SUPPORT] LPS-98519 Prepend context path to dynamic-data-mapping-form-builder CSS

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76236. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/29783e94acf5~1...29783e94acf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
