### PR TITLE
LPS-94071

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72253. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
