### PR TITLE
LPS-87601 Add integration tests to check audit fields in the get feature

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66315. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/70cbc94e0388~1...70cbc94e0388) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66316. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/366a025ac2bf~1...366a025ac2bf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
