### PR TITLE
LPS-91227 including poll question and vote when exporting

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69604. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ddbd282d8b4c~1...ddbd282d8b4c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
