### PR TITLE
LPS-95080 getting pages from context to get field options

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
cc: @alinedoleron

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/465. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
