### PR TITLE
LPS-85451 Tests for new Upgrade Processes

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Haha sorry about that! I'll fix this as soon as I finish working on the https://github.com/jeyvison/liferay-portal/pull/153

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
Third time's the charm

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/164. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/a8aaaedca673~1...a8aaaedca673) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
