### PR TITLE
LPS-84292 Use new APIs

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@jeyvison This is a work in progress pull request.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/100. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/6fe908eed661~4...6fe908eed661) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/101. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/174868894e26~5...174868894e26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/102. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/82915ae3f36d~5...82915ae3f36d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/103. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/6cc25e0a32dd~6...6cc25e0a32dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62372. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/fe3df3111a64~7...fe3df3111a64) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62391. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ff20ead23ca7~6...ff20ead23ca7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/106. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ff20ead23ca7~6...ff20ead23ca7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
