### PR TITLE
LPS-95267 Load a data layout previously stored

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jeyvison** [comment]
@leoadb , can you please fix the conflict? thanks!

**Comment by leoadb** [comment]
@jeyvison Done!

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/375. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/508b28b002c6~6...508b28b002c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/376. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/76e75f0a2b03~6...76e75f0a2b03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/377. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/da7d407abcec~6...da7d407abcec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73604. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/524a91b2631f~10...524a91b2631f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73640. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/556967164afb~11...556967164afb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
