### PR TITLE
LPS-104247 Accumulate nested field values

### PR DESCRIPTION
**Pull request by JavierMoral**
This pull fixes LPS-104247
It changes a class that originally belonged to WCM but was moved to DDM in LPS-96705
Could you please take a look at it?

Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hello @JavierMoral :) I'm currently on vacation . Can you please send it to @leoadb? Thanks a lot :)

**Comment by JavierMoral** [comment]
I will
Thanks

**Comment by JavierMoral** [comment]
ci:close

**Pull request closed without merging**
