### PR TITLE
LPS-88190 Form field validation not working for element sets

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

Could you please review this pull request?

The issue is that in https://github.com/jeyvison/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-expression/src/main/java/com/liferay/dynamic/data/mapping/expression/internal/DDMExpressionEvaluatorVisitor.java#L264 `variableValue == null` if the field was added through an element set.
Although `variableValue` is not present in `_variables`, and entry with the key variable<elementsetcode> will be present in the map, with the value entered by the user.
I solved the issue reported by the customer by assigning the value of the element set entry to `variableValue`.

Please let me know what you think of this. 

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65706. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Thank you for forwarding, @jeyvison !

**Pull request closed without merging**
