### PR TITLE
[TECHNICAL-SUPPORT] LPS-79011

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-79011

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Hi @jeyvison , 
I think this failures are not related with this PR because are different than these other test for the same PR: https://github.com/JosemariaMunoz/liferay-portal/pull/26
Thanks!

**Comment by jeyvison** [comment]
ci:test

**Comment by jeyvison** [comment]
Hey @pcwhite, can we add a poshi test for this case? Thanks :)

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56605. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
