### PR TITLE
LPS-96346 Fix unit tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74534. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/39672d93b065~1...39672d93b065) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
