### PR TITLE
LPS-117408 Include structure description in the form data to be posted

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-117408

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
