### PR TITLE
LPS-108755

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/87456

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/716. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/87ff1bb0d1ef~3...87ff1bb0d1ef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/717. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/922571be97bd~5...922571be97bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
