### PR TITLE
LPS-87919

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66053

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66131. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/f108883934af~3...f108883934af) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66184. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/0c314ad9d62a~4...0c314ad9d62a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66188. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/4f5b21ab4360~4...4f5b21ab4360) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
