### PR TITLE
LPS-93708 SF

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74185. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/86dfbdaf6bae~1...86dfbdaf6bae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hey @gabrielwas , see 86dfbda

**Comment by gabrielwas** [comment]
thanks, @jeyvison

**Pull request closed without merging**
