### PR TITLE
[TECHNICAL-SUPPORT] LPS-89444

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Brian:
>https://issues.liferay.com/browse/LPS-89444
>
> The issue here is that additional/duplicate Numerical Fields are permitting alphabetical characters rather than only allowing numerical characters.
> 
> The reason for this issue is that for additional/duplicate Numerical Fields, the check run here: [link](https://github.com/liferay/liferay-portal/blob/ea96bc2b49a04790ce4e662a7a98b244ebc43cc3/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/numeric/numeric_field.js#L151-L153) prevents [applyMask](https://github.com/liferay/liferay-portal/blob/ea96bc2b49a04790ce4e662a7a98b244ebc43cc3/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/numeric/numeric_field.js#L66-L93) from being called which is the method that enforces the numerical rule of the field.
> 
> The solution here is simple in that we need to remove the unnecessary check being done because the rule enforcing should be done regardless of whether the fields are of the same type.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/67163
Thanks!

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/98566. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-app-builder/liferay-portal/pull/219. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/15813d14b15e~1...15813d14b15e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
