### PR TITLE
[TECHNICAL-SUPPORT] LPS-99662

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @matthewchan1

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/77167. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77169. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
