### PR TITLE
[TECHNICAL SUPPORT] LPS-98669

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
There are some pages that are using  liferay-ddm:html taglib, but they are missing dynamic-data-mapping-web CSS, causing some bugs.

To avoid that, I am including DDMWebTopHeadDynamicInclude inside of the taglib

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @jeyvison 

I executed CI tests in this PR and there were no unique failures, see:

- https://github.com/jorgediaz-lr/liferay-portal/pull/225#issuecomment-518141144

So that failure is unrelated to my changes.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76592. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
