### PR TITLE
LPS-83662 When a Role is deleted, their accompanying Kaleo Task Assignments should be deleted as well

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

Could you please review this pull request?

I implemented this solution following the suggestions @drewbrokke made in https://github.com/drewbrokke/liferay-portal/pull/534#issuecomment-414780796.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hey @jeyvison 

I was wondering if by any chance you could manage to find the time to review the pull request?
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hi @IstvanD , Sorry for the delay in reviewing this. One thing that worries me is the lack of feedback to the users that wouldn't know what happened to their tasks. It would mislead them to believe it's about when it's not. I think we should inform the user that is deleting the Role that the associated workflow tasks will be deleted. 

I don't know if we can inform the users in that role too, since the role is being deleted and i don't know if the are "migrated" to another role, but if we could we definitely should. 

What you think @drewbrokke?

**Comment by IstvanD** [comment]
Hey @jeyvison, @drewbrokke,

Maybe the message in the deletion confirmation dialog should be changed?
https://github.com/liferay/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/view.jsp#L116

Thanks,
István

**Comment by jeyvison** [comment]
@IstvanD , i agree.

**Comment by drewbrokke** [comment]
Hey everyone, sorry I've been MIA for a bit.  I'm ok with updating the confirmation dialog text.  It will provide enough direction for an admin to make an informed decision without restricting their ability to delete the role.

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-data-engine/liferay-portal/pull/108. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/d2d1249fd315~2...d2d1249fd315) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
