### PR TITLE
LPS-118762 verifying how many links has the structure

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/859. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c9065a8e534f~1...c9065a8e534f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
