### PR TITLE
LPS-95698 disable user input until form is fully rendered

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
cc: @alinedoleron

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi, I've altered the commit moving the css to form renderer to also have effect when the form is on a page fragment.
Going to run ci test again.
Thanks!

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/463. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
