### PR TITLE
[TECHNICAL-SUPPORT] LPS-86805

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @ChrisKian

Notes from Chris:
>https://issues.liferay.com/browse/LPS-86805
>
>Resolves an issue caused by my earlier fix LPS-85726 which causes the "submit for publication" button to not be visible, and instead a "ready for publication" slider to appear.  This is because when retrieving the workflowDefinitionLink, we search by the staging groupId, when in fact, workflows are only stored by the live groupIds, so nothing is returned.
>
>You can see in other methods of the WorkflowDefinitionLinkLocalServiceImpl class, the groupId is transformed into the live groupId before fetching, deleting, updating, etc.
>
>Let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failures seem unrelated.  My changes should cause no compilations errors, nor should any template-related tests start failing.

**Comment by jeyvison** [comment]
Hello @SamZiemer  and @ChrisKian :) Sorry for the delay in reviewing your PR but i'm planning to review it ''till tomorrow. Thanks a lot for the fix =D

**Comment by jeyvison** [comment]
Hello @SamZiemer  and @ChrisKian. Can you please foward this PR to @inacionery ? He'll take of the workflow PR's starting now :) Thanks a lot for your fix =D

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/inacionery/liferay-portal/pull/147. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just fowarded to him :)

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/liferay-app-builder/liferay-portal/pull/151. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/aa724adddc2b~2...aa724adddc2b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
