### PR TITLE
LPS-85785 Fix compiling and rebasing

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

I have fixed the compiling and rebasing failures that were discovered in https://github.com/jeyvison/liferay-portal/pull/526

Could you please review?

Thank you and best regards,
István

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
hi @IstvanD . We are getting a SF problem in this pull. Can you take a look? No need to resend if you want, just push force. Thx :)

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76463. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/1d6f2d7ad010~1...1d6f2d7ad010) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76471. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3e7e90c49873~2...3e7e90c49873) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76533. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3e7e90c49873~2...3e7e90c49873) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76757. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3e7e90c49873~2...3e7e90c49873) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
