### PR TITLE
LPS-100419 SF

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/nhpatt/liferay-portal/pull/165. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/569e8bb22d49~2...569e8bb22d49) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78070. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/26e8a6a4fd14~2...26e8a6a4fd14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78484. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/157a686586df~4...157a686586df) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78508. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/867c6795f2f8~4...867c6795f2f8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
