### PR TITLE
LPS-93057 Add test scenario for data layouts to REST resource

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74532. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c78838e80a0b~1...c78838e80a0b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
