### PR TITLE
[TECHNICAL-SUPPORT] LPS-89935

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-89935
> https://issues.liferay.com/browse/LPP-32782
> 
> Hello Sam, I've made a bunch of small changes to get the forms required fields to work properly. Probably the easiest way to see the old behavior compared to the new behavior is to view the videos attached to the LPP. There's also a Form export for master attached for testing.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/68386
Thank you @joshuacords, @SamZiemer

**Pull request closed without merging**
