### PR TITLE
LPS-84760 Fix other compilation errors produced by autogenerated tasks

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
hi @ealonso ! I tried to test your PR but i'm not able to select a structure when creating a web content. After i click the structure name, nothing happens and a error is shown in console. It's happening in master. Follows the gif:

web_content

**Comment by Seiphon** [comment]
Hi @jeyvison 

I don't think the error is related to this fix. You can choose structure directly after you click add button rather than choose Basic Web Content, it will avoid this error. For the error you found, maybe we can create a new LPS ticket to solve it later. 

Br,
Seiphon

**Comment by ealonso** [comment]
Hey @jeyvison,

This is the fix for the error, https://github.com/brianchandotcom/liferay-portal/pull/63054

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
It looks good to me! :)

Just sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/63126.

Thanks, guys! @robertoDiaz @ealonso

**Comment by pedroqueiroz** [comment]
ci:close

**Comment by pedroqueiroz** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Hey @robertoDiaz,

Brian Chan will not accept the PR if we don't fix that problems, as you can see in his comment [here](https://github.com/brianchandotcom/liferay-portal/pull/63126#issuecomment-422086721).

We will need to fix the generator first in order to move your PR forward. We will discuss with Bruno Basto in order to see the best approach for this change.

Sorry about that.

**Comment by pedroqueiroz** [comment]
Here is the Alloy ticket which we will fix the issue: https://issues.liferay.com/browse/AUI-3155. 

We will talk to our PM to include this in our Sprint. :)

**Comment by robertoDiaz** [comment]
Hi @jeyvison and @pedroqueiroz 

What is the current status of this??

Was it merged in master?? Do we have to rebase the code??

**Comment by jeyvison** [comment]
Hello @robertoDiaz :) I just talked with @pedroqueiroz and he told that this was already merged with the TagLib. If you guys didn't do it so i'll kindly ask you to resend the pull request regenerating the taglib with the gradle task. 

Fell free to talk with me by slack if you wanna help or clarification on this :)

**Comment by robertoDiaz** [comment]
Hi, I'll check it  and resend the code if needed.

Thanks!!

**Comment by jeyvison** [comment]
Sure, just looked at the LPS and it's already closed too.

https://issues.liferay.com/browse/LPS-84760

**Pull request closed without merging**
