### PR TITLE
LPS-88197 Avoid overwritting target groupId in Global site initial live-staging publication

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:staging

**Comment by jeyvison** [comment]
ci:test:help

**Comment by jeyvison** [comment]
ci:help

**Comment by jeyvison** [comment]
ci:test:abort

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:test:staging

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/65892
Thanks!

**Pull request closed without merging**
