### PR TITLE
LPS-81710 Remove Matching Existing DDMFormFieldValues

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test

**Comment by brianikim** [comment]
ci:reopen

**Comment by natocesarrego** [comment]
Thanks for reopening this pull, @brianikim.

@jeyvison, the CI failures, from what I could see, aren't related to the modification of this pull.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62140. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
