### PR TITLE
[TECHNICAL SUPPORT] LPS-100132 Field should not be evaluated if Rule decided that it is not visible

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-100132

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77406. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/3a14b48894bc~1...3a14b48894bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
