### PR TITLE
LPS-85042

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The test failures are not related to my changes.

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63224. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
