### PR TITLE
LPS-90047 showing publish alert

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68719. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/77a59e5c0fc0~1...77a59e5c0fc0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
