### PR TITLE
LPS-88995 DDM upgrade to 7.1 fails with NPE due to DDMContent table's stats being locked

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jeyvison 

Could you please review this pull request?

The issue is very similar to LPS-88790 but it is not the same. Instead of DDMStructure, this issue regards the DDMContent.
Moreover, it is reproducible not only on 7.1.x but on master too. Therefore, I send the pull request to master.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:test:upgrade

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/66666
Thanks!

**Pull request closed without merging**
