### PR TITLE
LPS-84386 Check for null before getting value

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/95. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/e83119e1dd5a~2...e83119e1dd5a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62142. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/e83119e1dd5a~2...e83119e1dd5a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
