### PR TITLE
LPS-99035 Set default value to storage type

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77823. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/47a50c6ce5ff~1...47a50c6ce5ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
