### PR TITLE
LPS-96153 Fix test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74700. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/16e6668be989~1...16e6668be989) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
