### PR TITLE
LPS-118436 Get value from user defaultLanguage because value is an object of translated languages

### PR DESCRIPTION
**Pull request by interaminense**
cc: @gabrielwas, @kevenleone, @albinojunior

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
@interaminense the poshi and js test erros are not flaky. Can you please take a look at this? Thanks :)

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
resent: #820

**Pull request closed without merging**
