### PR TITLE
LPS-92838 Increase timeout for search tests

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison please could you review this pr? Thanks

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/70404. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
