### PR TITLE
LPS-98124 Verify if names are empty

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83968. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/bd635540d1e3~3...bd635540d1e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83979. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/9560c8c4beaf~3...9560c8c4beaf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
