### PR TITLE
[TECHNICAL SUPPORT] LPS-119795 Unable to delete translations of the web content

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

Root cause: We catch the 'inputLocalized:defaultLocaleChanged' event in both [ddm_form.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L4025-L4035) and input_localized.js
When we handle the event in [input_localized.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/input_localized.js#L258) we also fire  ['inputLocalized:localeChanged' event](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/input_localized.js#L289-L292)
This event is also caught by [ddm_form.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L516-L529)

The problem is updateLocalizationMap is [depending on the defaultLocale](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L1153) and it will be called before we actually change the default Locale in ddm_form.js

My solution was to make sure we change the defaultLocale in ddm_form.js before we actually receive and handle the localeChanged event.

I also had to adjust the if statements when we update the localisationMap to finalise the fix.

Please review my changes

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
