### PR TITLE
LPS-97896 Add method to update DDMStructure without making it necessary to update its version

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75381. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/0136402d49e3~3...0136402d49e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
