### PR TITLE
LPS-118114 Transform to a Map compatible with the data engine rest api

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/854. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/62c642f0f8a8~3...62c642f0f8a8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/855. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/5a226f5db7fb~3...5a226f5db7fb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
