### PR TITLE
[TECHNICAL-SUPPORT] LPS-97437

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim

Notes from Brian:
> https://issues.liferay.com/browse/LPS-97437
> 
> Fairly straightforward issue. 
> 
> Back button is not being shown in data definition page because our current check prevents back button from showing if the tab list is not empty.
> 
> The fix is to improve the logic by checking whether the tab list contains more than one tabs.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75347. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/248cbd4bcb36~1...248cbd4bcb36) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
