### PR TITLE
LPS-106424 Use permission thread local

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:relevant:app-builder

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/666. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83062. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/571438ef8ffd~1...571438ef8ffd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83105. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/bf62b06c149d~1...bf62b06c149d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83108. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/f96dd00b98e8~1...f96dd00b98e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83121. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ab57360ff890~3...ab57360ff890) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83124. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c8dc073142b7~1...c8dc073142b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83126. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/2666244b9025~1...2666244b9025) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83128. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/c385d749f733~1...c385d749f733) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83129. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/2181fd9233be~1...2181fd9233be) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83131. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/9609b2547bc0~1...9609b2547bc0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83132. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/ff1449e04c92~2...ff1449e04c92) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83135. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/2979f8329fda~1...2979f8329fda) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
