### PR TITLE
LPS-99569 Add condition if there is no keywords

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/613. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/7eb73cd57282~2...7eb73cd57282) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78784. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/eee2226d69b2~2...eee2226d69b2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78797. [See changes here.](https://github.com/jeyvison/liferay-portal/compare/db6d076291ff~2...db6d076291ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
