### PR TITLE
LPS-93142 Add random data definition with field and validation

### PR DESCRIPTION
**Pull request by mclomello**
@jeyvison could u review this pr?

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:relevant

**Pull request closed without merging**
